import phCardNews from '@/assets/placeholders/ph-card-news.png';

export const mockNews = [
    {
      id: 1,
      title: 'Новое законодательство по капитальному ремонту в ЖКХ',
      description: 'В России введены новые правила для капитального ремонта в жилых домах, которые улучшат безопасность и качество строительства.',
      fullTextCharCount: 1200,
      imageUrl: 'https://www.pnp.ru/upload/entities/2020/03/15/article/detailPicture/ef/83/a6/43/efc93793e6cbaaa1c54b7d9e0831657a.jpg',
      publishDate: '2025-01-19',
      slug: 'novoe-zakonodatelstvo-po-kapitalnomu-remontu-v-zhkh',
    },
    {
      id: 2,
      title: 'Цены на коммунальные услуги в 2025 году: что изменится?',
      description: 'Правительство России анонсировало повышение тарифов на коммунальные услуги в следующем году.',
      fullTextCharCount: 1500,
      imageUrl: 'https://static.mk.ru/upload/entities/2022/06/25/11/articles/detailPicture/2d/74/d1/a2/84e25e9a763ee5b688ec08f9e08f6db7.jpg',
      publishDate: '2025-01-18',
      slug: 'tseny-na-kommunalnye-uslugi-v-2025-godu-chto-izmenitsya',
    },
    {
      id: 3,
      title: 'Новые стандарты энергоэффективности в жилых зданиях',
      description: 'Скоро вступят в силу новые стандарты, направленные на повышение энергоэффективности жилых домов.',
      fullTextCharCount: 1300,
      imageUrl: 'https://odin.ru/img/gallery/2021/10/ZhKKh-tekst-tn2.jpg',
      publishDate: '2025-01-17',
      slug: 'novye-standarty-energoeffektivnosti-v-zhilykh-zdaniyakh',
    },
    {
      id: 4,
      title: 'Государственная программа для улучшения качества воды в домах',
      description: 'Госпрограмма направлена на замену старых водопроводных систем и улучшение качества питьевой воды.',
      fullTextCharCount: 1400,
      imageUrl: 'http://www.konserg.ru/upload/resize_cache/iblock/af8/660_360_1/af88c80dd04c71842cbe8fd36f89450c.jpg',
      publishDate: '2025-01-16',
      slug: 'gossudarstvennaya-programma-dlya-uluchsheniya-kachestva-vody-v-domakh',
    },
    {
      id: 5,
      title: 'Снижение затрат на обслуживание многоквартирных домов',
      description: 'Местные власти предлагают новые методы для снижения расходов на содержание многоквартирных домов.',
      fullTextCharCount: 1600,
      imageUrl: 'https://cs13.pikabu.ru/post_img/big/2024/01/12/7/1705057262148264801.jpg',
      publishDate: '2025-01-15',
      slug: 'snizhenie-zatrat-na-obsluzhivanie-mnogokvartirnykh-domov',
    },
    {
      id: 6,
      title: 'Подготовка к отопительному сезону',
      description: 'В крупных городах России стартуют масштабные работы по подготовке к отопительному сезону.',
      fullTextCharCount: 1700,
      imageUrl: 'https://images.cnscdn.com/6/2/9/7/629744cf2f617b500e6a9d0ec21c09a9/original.jpg',
      publishDate: '2025-01-14',
      slug: 'podgotovka-k-otopitelnomu-sezonu',
    },
    {
      id: 7,
      title: 'Новые технологии для улучшения отопления в многоквартирных домах',
      description: 'Внедрение новых технологий для более эффективного отопления многоквартирных домов позволит снизить расходы на энергоносители.',
      fullTextCharCount: 1100,
      imageUrl: phCardNews,
      publishDate: '2025-01-13',
      slug: 'novye-tekhnologii-dlya-uluchsheniya-otopleniya-v-mnogokvartirnykh-domakh',
    },
    {
      id: 8,
      title: 'Перевод жилых домов на энергоэффективные системы отопления',
      description: 'В России начнется перевод жилых домов на энергоэффективные системы отопления для улучшения экологии.',
      fullTextCharCount: 2000,
      imageUrl: phCardNews,
      publishDate: '2025-01-12',
      slug: 'perevod-zhilykh-domov-na-energoeffektivnye-sistemy-otopleniya',
    },
    {
      id: 9,
      title: 'Современные технологии для повышения безопасности в жилых домах',
      description: 'Технологии умных домов помогут повысить безопасность и комфорт жителей многоквартирных домов.',
      fullTextCharCount: 1200,
      imageUrl: phCardNews,
      publishDate: '2025-01-11',
      slug: 'sovremennye-tekhnologii-dlya-povysheniya-bezopasnosti-v-zhilykh-domakh',
    },
    {
      id: 10,
      title: 'Услуги по управлению многоквартирными домами становятся доступнее',
      description: 'Снижение стоимости услуг по управлению многоквартирными домами станет доступным для большинства собственников жилья.',
      fullTextCharCount: 1400,
      imageUrl: phCardNews,
      publishDate: '2025-01-10',
      slug: 'uslugi-po-upravleniyu-mnogokvartirnymi-domami-stanovyatsya-dostupnee',
    },
    {
      id: 11,
      title: 'Снижение налогов на содержание многоквартирных домов',
      description: 'Предлагается снижение налогов на содержание многоквартирных домов для улучшения качества обслуживания.',
      fullTextCharCount: 1600,
      imageUrl: phCardNews,
      publishDate: '2025-01-09',
      slug: 'snizhenie-nalogov-na-soderzhanie-mnogokvartirnykh-domov',
    },
    {
      id: 12,
      title: 'Развитие инфраструктуры ЖКХ в отдаленных регионах',
      description: 'Власти планируют усиленное развитие инфраструктуры ЖКХ в отдаленных и сельских районах России.',
      fullTextCharCount: 1500,
      imageUrl: phCardNews,
      publishDate: '2025-01-08',
      slug: 'razvitiye-infrastruktury-zhkh-v-otdalennykh-regionakh',
    },
    {
      id: 13,
      title: 'Поддержка инициатив по озеленению придомовых территорий',
      description: 'Новая программа будет поддерживать инициативы по озеленению придомовых территорий в городах.',
      fullTextCharCount: 1300,
      imageUrl: phCardNews,
      publishDate: '2025-01-07',
      slug: 'podderzhka-initsiativ-po-ozeleleniyu-pridomovykh-territoriy',
    },
    {
      id: 14,
      title: 'Проблемы с вывозом мусора в крупных городах России',
      description: 'Обострение проблемы с вывозом мусора в крупных городах России требует срочных решений.',
      fullTextCharCount: 1800,
      imageUrl: phCardNews,
      publishDate: '2025-01-06',
      slug: 'problemy-s-vyvozem-musora-v-krupnykh-gorodakh-rossii',
    },
    {
      id: 15,
      title: 'Обновление законодательства в области ЖКХ на 2025 год',
      description: 'Составлен новый законопроект, который меняет правила в сфере ЖКХ в 2025 году.',
      fullTextCharCount: 1500,
      imageUrl: phCardNews,
      publishDate: '2025-01-05',
      slug: 'obnovlenie-zakonodatelstva-v-oblasti-zhkh-na-2025-god',
    },
    {
        id: 16,
        title: 'Перераспределение средств на капитальный ремонт жилых домов',
        description: 'Внесены изменения в программу финансирования капитального ремонта многоквартирных домов.',
        fullTextCharCount: 1600,
        imageUrl: phCardNews,
        publishDate: '2025-01-04',
        slug: 'pereraspredelenie-sredstv-na-kapitalnyy-remont-zhilykh-domov',
      },
      {
        id: 17,
        title: 'Обновление системы водоснабжения в мегаполисах',
        description: 'Запускается программа по модернизации водоснабжения в крупнейших городах страны.',
        fullTextCharCount: 1400,
        imageUrl: phCardNews,
        publishDate: '2025-01-03',
        slug: 'obnovlenie-sistemy-vodosnabzheniya-v-megapolisisakh',
      },
      {
        id: 18,
        title: 'Инновации в области отопления жилых домов',
        description: 'Представлены новые технологии для повышения эффективности систем отопления в многоквартирных домах.',
        fullTextCharCount: 1500,
        imageUrl: phCardNews,
        publishDate: '2025-01-02',
        slug: 'innovatsii-v-oblasti-otopleniya-zhilykh-domov',
      },
      {
        id: 19,
        title: 'Внедрение «умных» технологий для управления многоквартирными домами',
        description: 'Множество новшеств в области «умного» управления многоквартирными домами, включая автоматизацию обслуживания.',
        fullTextCharCount: 1700,
        imageUrl: phCardNews,
        publishDate: '2025-01-01',
        slug: 'vnedrenie-umnykh-tekhnologiy-dlya-upravleniya-mnogokvartirnymi-domami',
      },
      {
        id: 20,
        title: 'Проблемы с обеспечением безопасностью на придомовых территориях',
        description: 'Ситуация с безопасностью на придомовых территориях в многоквартирных домах требует вмешательства властей.',
        fullTextCharCount: 1400,
        imageUrl: phCardNews,
        publishDate: '2024-12-31',
        slug: 'problemy-s-obespecheniem-bezopasnostyu-na-pridomovykh-territoriyakh',
      },
      {
        id: 21,
        title: 'Увеличение финансирования для ремонта лифтов в многоквартирных домах',
        description: 'На ремонт и замену лифтов в многоквартирных домах выделяются дополнительные средства из бюджета.',
        fullTextCharCount: 1300,
        imageUrl: phCardNews,
        publishDate: '2024-12-30',
        slug: 'uvelichenie-finansirovaniya-dlya-remonta-liftov-v-mnogokvartirnykh-domakh',
      },
      {
        id: 22,
        title: 'Новые требования к обслуживанию систем вентиляции в домах',
        description: 'Министерство ЖКХ представило новые требования по обслуживанию вентиляционных систем в многоквартирных домах.',
        fullTextCharCount: 1600,
        imageUrl: phCardNews,
        publishDate: '2024-12-29',
        slug: 'novye-trebovaniya-k-obsluzhivaniyu-sistem-ventilyatsii-v-domakh',
      },
      {
        id: 23,
        title: 'Использование возобновляемых источников энергии в ЖКХ',
        description: 'Внедрение солнечных панелей и других возобновляемых источников энергии в ЖКХ обещает существенные экономии для жителей.',
        fullTextCharCount: 1800,
        imageUrl: phCardNews,
        publishDate: '2024-12-28',
        slug: 'ispolzovanie-vozobnovlyaemykh-istochnikov-energii-v-zhkh',
      },
      {
        id: 24,
        title: 'Модернизация электросетей для улучшения качества энергии в домах',
        description: 'Электросети подвергнутся модернизации для повышения качества подачи электричества в жилые дома.',
        fullTextCharCount: 1500,
        imageUrl: phCardNews,
        publishDate: '2024-12-27',
        slug: 'modernizatsiya-elektrosetey-dlya-uluchsheniya-kachestva-energii-v-domakh',
      },
      {
        id: 25,
        title: 'Правительство запустило программу для улучшения благоустройства дворов',
        description: 'Запуск новой программы, которая будет финансировать проекты по благоустройству дворовых территорий.',
        fullTextCharCount: 1200,
        imageUrl: phCardNews,
        publishDate: '2024-12-26',
        slug: 'pravitelstvo-zapustilo-programmu-dlya-uluchsheniya-blagoustroystva-dvorov',
      },
      {
        id: 26,
        title: 'Обновление программы субсидий на коммунальные услуги',
        description: 'В России обновлена программа субсидий на оплату коммунальных услуг для малоимущих семей.',
        fullTextCharCount: 1400,
        imageUrl: phCardNews,
        publishDate: '2024-12-25',
        slug: 'obnovlenie-programmy-subsidiy-na-kommunalnye-uslugi',
      },
      {
        id: 27,
        title: 'Планируется строительство новых очистных сооружений в крупных городах',
        description: 'Запланировано строительство новых очистных сооружений для улучшения экологии и качества воды.',
        fullTextCharCount: 1300,
        imageUrl: phCardNews,
        publishDate: '2024-12-24',
        slug: 'planirovano-stroitelstvo-novykh-ochistnykh-sooruzheniy-v-krupnykh-gorodakh',
      },
      {
        id: 28,
        title: 'Тарифы на газ и отопление для населения останутся без изменений',
        description: 'Новый законопроект предполагает заморозку тарифов на газ и отопление для населения в следующем году.',
        fullTextCharCount: 1100,
        imageUrl: phCardNews,
        publishDate: '2024-12-23',
        slug: 'tarify-na-gaz-i-otoplenie-dlya-naseleniya-ostanutsya-bez-izmeneniy',
      },
      {
        id: 29,
        title: 'Цифровизация ЖКХ: проекты на 2025 год',
        description: 'В 2025 году в России начнется внедрение новых цифровых решений для управления системой ЖКХ.',
        fullTextCharCount: 1200,
        imageUrl: phCardNews,
        publishDate: '2024-12-22',
        slug: 'tsifrovizatsiya-zhkh-proekty-na-2025-god',
      },
      {
        id: 30,
        title: 'Программа по повышению энергоэффективности в ЖКХ',
        description: 'Запуск новой программы, направленной на улучшение энергоэффективности объектов ЖКХ по всей стране.',
        fullTextCharCount: 1300,
        imageUrl: phCardNews,
        publishDate: '2024-12-21',
        slug: 'programma-po-povysheniyu-energoeffektivnosti-v-zhkh',
      },
      {
        id: 31,
        title: 'Пересмотр стандартов по освещению в многоквартирных домах',
        description: 'Будут пересмотрены стандарты освещения в многоквартирных домах, с целью улучшения качества жизни жителей.',
        fullTextCharCount: 1400,
        imageUrl: phCardNews,
        publishDate: '2024-12-20',
        slug: 'peresmotr-standartov-po-osveshcheniyu-v-mnogokvartirnykh-domakh',
      },
      {
        id: 32,
        title: 'Строительство жилых комплексов с использованием экологичных материалов',
        description: 'Новые жилые комплексы будут строиться с использованием экологичных и энергоэффективных материалов.',
        fullTextCharCount: 1600,
        imageUrl: phCardNews,
        publishDate: '2024-12-19',
        slug: 'stroitelstvo-zhilykh-kompleksov-s-ispolzovaniem-ekologichnykh-materialov',
      },
      {
        id: 33,
        title: 'Реформа системы начисления платежей за ЖКХ',
        description: 'Представлены новшества в системе начисления платежей за коммунальные услуги в многоквартирных домах.',
        fullTextCharCount: 1800,
        imageUrl: phCardNews,
        publishDate: '2024-12-18',
        slug: 'reforma-sistemy-nachisleniya-platezhey-za-zhkh',
      },
      {
        id: 34,
        title: 'Новые подходы к ремонту кровель в многоквартирных домах',
        description: 'Министерство ЖКХ представило новый подход к ремонту кровель в многоквартирных домах для повышения их долговечности.',
        fullTextCharCount: 1700,
        imageUrl: phCardNews,
        publishDate: '2024-12-17',
        slug: 'novye-podkhody-k-remontu-krovel-v-mnogokvartirnykh-domakh',
      },
      {
        id: 35,
        title: 'Расширение доступа к услугам по управлению многоквартирными домами',
        description: 'В России развивается рынок услуг по управлению многоквартирными домами с целью повышения доступности и качества услуг.',
        fullTextCharCount: 1500,
        imageUrl: phCardNews,
        publishDate: '2024-12-16',
        slug: 'rasshirenie-dostupa-k-uslugam-po-upravleniyu-mnogokvartirnymi-domami',
      }
  ];